version: '3.8'
networks:
  postgres_db:
    driver: bridge

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME} 
      ENCODING: 'UTF8'
      LC_COLLATE: 'C.UTF-8'
      LC_CTYPE: 'C.UTF-8'
    ports:
      - "${POSTGRES_PORT}:5432"
    command: postgres -c 'max_connections=300'
    volumes:
      - db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 30s
      timeout: 5s
      retries: 5

    restart: always
    networks:
      - postgres_db

  migrate_db:
    image: jagernau/monitoringdb:migrate_db
    depends_on:
      - db
    networks:
      - postgres_db

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}

volumes:
  db_data:
