from os import environ as envi

# Глонасс
GLONASS_HOST=envi['GLONASS_HOST']
GLONASS_LOGIN=envi['GLONASS_LOGIN']
GLONASS_PASSWORD=envi['GLONASS_PASSWORD']

# Форт
FORT_HOST=envi['FORT_HOST']
FORT_LOGIN=envi['FORT_LOGIN']
FORT_PASSWORD=envi['FORT_PASSWORD']

# Wialon
WIALON_HOST=envi['WIALON_HOST']
WIALON_TOKEN=envi['WIALON_TOKEN']

# Wialon local
WIALON_LOCAL_HOST=envi['WIALON_LOCAL_HOST']
WIALON_LOCAL_TOKEN=envi['WIALON_LOCAL_TOKEN']

# Scout
SCAUT_HOST=envi['SCAUT_HOST']
SCAUT_LOGIN=envi['SCAUT_LOGIN']
SCAUT_PASSWORD=envi['SCAUT_PASSWORD']

# Era
ERA_HOST=envi['ERA_HOST']
ERA_LOGIN=envi['ERA_LOGIN']
ERA_PASSWORD=envi['ERA_PASSWORD']

# Database
DB_HOST=envi['DB_HOST']

# Postgres
POSTGRES_USER=envi['POSTGRES_USER']
POSTGRES_DB_NAME=envi['POSTGRES_DB_NAME']
POSTGRES_PASSWORD=envi['POSTGRES_PASSWORD']
POSTGRES_PORT=envi['POSTGRES_PORT']

# MySQL
MYSQL_USER=envi['MYSQL_USER']
MYSQL_DB_NAME=envi['MYSQL_DB_NAME']
MYSQL_PASSWORD=envi['MYSQL_PASSWORD']
MYSQL_PORT=envi['MYSQL_PORT']

# Yandex Disk
DISK_TOKEN=envi['DISK_TOKEN']

# Time active
TIME_ACTIVE=str(envi['TIME_ACTIVE'])

connection_postgres = f"postgresql+psycopg2://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{DB_HOST}:{POSTGRES_PORT}/{POSTGRES_DB_NAME}"

connection_mysql = f"mysql+mysqlconnector://{MYSQL_USER}:{MYSQL_PASSWORD}@{DB_HOST}:{MYSQL_PORT}/{MYSQL_DB_NAME}"
