from dotenv import dotenv_values

config = dotenv_values(".env")


DB_HOST=config['DB_HOST']

POSTGRES_USER=config['POSTGRES_USER']
POSTGRES_DB_NAME=config['POSTGRES_DB_NAME']
POSTGRES_PASSWORD=config['POSTGRES_PASSWORD']
POSTGRES_PORT=config['POSTGRES_PORT']

SCOUT_TREE_LOGIN = config["17_SCOUT_365_LOGIN"]
SCOUT_TREE_PASSWORD = config["17_SCOUT_365_PASSWORD"]
SCOUT_TREE_URL = config["17_SCOUT_365_URL"]
SCOUT_TREE_BASED_TOKEN = config["17_SCOUT_365_BASED_TOKEN"]

connection_postgres = f"postgresql+psycopg2://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{DB_HOST}:{POSTGRES_PORT}/{POSTGRES_DB_NAME}"

