FROM python:3.10
COPY . /monitoring_db_autosave
WORKDIR /monitoring_db_autosave
# Глонасс
ENV GLONASS_HOST=${GLONASS_HOST}
ENV GLONASS_LOGIN=${GLONASS_LOGIN}
ENV GLONASS_PASSWORD=${GLONASS_PASSWORD}

# Форт
ENV FORT_HOST=${FORT_HOST}
ENV FORT_LOGIN=${FORT_LOGIN}
ENV FORT_PASSWORD=${FORT_PASSWORD}

# Wialon
ENV WIALON_HOST=${WIALON_HOST}
ENV WIALON_TOKEN=${WIALON_TOKEN}

# Wialon local
ENV WIALON_LOCAL_HOST=${WIALON_LOCAL_HOST}
ENV WIALON_LOCAL_TOKEN=${WIALON_LOCAL_TOKEN}

# Scout
ENV SCAUT_HOST=${SCAUT_HOST}
ENV SCAUT_LOGIN=${SCAUT_LOGIN}
ENV SCAUT_PASSWORD=${SCAUT_PASSWORD}

# Era
ENV ERA_HOST=${ERA_HOST}
ENV ERA_LOGIN=${ERA_LOGIN}
ENV ERA_PASSWORD=${ERA_PASSWORD}

# Database
ENV DB_HOST=${DB_HOST}

# Postgres
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_PORT=${POSTGRES_PORT}

# MySQL
ENV MYSQL_USER=${MYSQL_USER}
ENV MYSQL_DB_NAME=${MYSQL_DB_NAME}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}
ENV MYSQL_PORT=${MYSQL_PORT}

# Yandex Disk
ENV DISK_TOKEN=${DISK_TOKEN}

# Time active
ENV TIME_ACTIVE=${TIME_ACTIVE}

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
